"""ML Research Platform — Reproducibility Analyzer.

Analyzes code generated by DeepCode against the original paper
to determine what was successfully implemented and what wasn't.

Produces a detailed report with:
  - Implementation completeness score (%)
  - Successfully implemented components
  - Failed or missing components
  - Error analysis
  - Suggestions for improvement
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class ComponentResult:
    """Analysis result for a single component.

    Attributes:
        name: Component name (e.g. "attention mechanism").
        status: Implementation status.
        confidence: Confidence score (0-1).
        notes: Additional notes.
        error: Error message if failed.
    """
    name: str = ""
    status: str = "unknown"  # implemented, partial, missing, failed
    confidence: float = 0.0
    notes: str = ""
    error: str = ""


@dataclass
class ReproducibilityReport:
    """Complete reproducibility analysis for a paper.

    Attributes:
        paper_id: Paper identifier.
        paper_title: Paper title.
        overall_score: Implementation completeness (0-100).
        components: Per-component analysis.
        generated_files: List of generated code files.
        total_lines: Total lines of generated code.
        errors: List of error messages.
        suggestions: Improvement suggestions.
        duration_seconds: Analysis duration.
    """
    paper_id: str = ""
    paper_title: str = ""
    overall_score: float = 0.0
    components: list[ComponentResult] = field(default_factory=list)
    generated_files: list[str] = field(default_factory=list)
    total_lines: int = 0
    errors: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)
    duration_seconds: float = 0.0


class ReproducibilityAnalyzer:
    """Analyzes DeepCode output against original paper.

    Usage:
        analyzer = ReproducibilityAnalyzer()
        report = analyzer.analyze(
            paper_id="2605.13153",
            paper_abstract="...",
            code_dir="/path/to/generated/code",
        )
        print(f"Score: {report.overall_score}%")
    """

    ANALYSIS_PROMPT = """Analyze the following generated code against the paper description.
For each key component mentioned in the paper, determine if it was successfully implemented.

Paper abstract/description:
{paper_desc}

Generated code files:
{file_list}

Code content (truncated):
{code_content}

Return JSON:
{{
    "overall_score": 0-100,
    "components": [
        {{
            "name": "component name",
            "status": "implemented|partial|missing|failed",
            "confidence": 0.0-1.0,
            "notes": "what was implemented",
            "error": "error message if any"
        }}
    ],
    "suggestions": ["suggestion 1", "suggestion 2"]
}}"""

    def __init__(self) -> None:
        self.provider = os.getenv("ML_DEFAULT_LLM_PROVIDER", "ollama")
        self.model = os.getenv("ML_DEFAULT_LLM_MODEL", "gemma4:31b-cloud")

    def analyze(
        self,
        paper_id: str,
        paper_abstract: str = "",
        paper_analysis: dict | None = None,
        code_dir: str | Path | None = None,
    ) -> ReproducibilityReport:
        """Analyze generated code against paper.

        Args:
            paper_id: Paper identifier.
            paper_abstract: Paper abstract text.
            paper_analysis: Detailed analysis dict (from analyzer).
            code_dir: Directory with generated code.

        Returns:
            ReproducibilityReport with detailed analysis.
        """
        report = ReproducibilityReport(paper_id=paper_id)

        # Collect generated code
        if code_dir and Path(code_dir).exists():
            code_dir = Path(code_dir)
            code_files = list(code_dir.rglob("*.py")) + list(code_dir.rglob("*.js"))
            report.generated_files = [str(f) for f in code_files]

            # Count lines
            total = 0
            code_content_parts = []
            for f in code_files[:10]:  # Limit to 10 files
                try:
                    content = f.read_text(encoding="utf-8", errors="ignore")
                    total += len(content.splitlines())
                    code_content_parts.append(
                        f"=== {f.name} ===\n{content[:2000]}"
                    )
                except Exception:
                    pass
            report.total_lines = total
            code_content = "\n\n".join(code_content_parts)[:8000]
        else:
            code_content = "(No generated code found)"
            report.errors.append("No code directory found")

        # Build paper description
        paper_desc = paper_abstract or ""
        if paper_analysis:
            key_contribs = paper_analysis.get("key_contributions_json", "")
            if isinstance(key_contribs, str):
                try:
                    key_contribs = json.loads(key_contribs)
                except (json.JSONDecodeError, TypeError):
                    key_contribs = []
            if key_contribs:
                paper_desc += "\n\nKey Contributions:\n" + "\n".join(
                    f"- {c}" for c in (key_contribs if isinstance(key_contribs, list) else [])
                )

        # If no code generated, return early
        if not report.generated_files:
            report.overall_score = 0.0
            report.components.append(ComponentResult(
                name="full_implementation",
                status="missing",
                notes="No code was generated",
            ))
            return report

        # LLM analysis
        try:
            result = self._analyze_with_llm(paper_desc, report.generated_files, code_content)
            report.overall_score = result.get("overall_score", 0)
            for comp in result.get("components", []):
                report.components.append(ComponentResult(
                    name=comp.get("name", ""),
                    status=comp.get("status", "unknown"),
                    confidence=comp.get("confidence", 0),
                    notes=comp.get("notes", ""),
                    error=comp.get("error", ""),
                ))
            report.suggestions = result.get("suggestions", [])
        except Exception as e:
            report.errors.append(f"LLM analysis failed: {e}")
            # Basic heuristic: if files exist, give base score
            report.overall_score = min(30, len(report.generated_files) * 10)

        return report

    def _analyze_with_llm(
        self, paper_desc: str, files: list[str], code: str
    ) -> dict:
        """Run LLM-based analysis."""
        from litellm import completion
        import litellm
        litellm.drop_params = True

        prompt = self.ANALYSIS_PROMPT.format(
            paper_desc=paper_desc[:3000],
            file_list="\n".join(f"- {f}" for f in files[:20]),
            code_content=code,
        )
        response = completion(
            model=f"{self.provider}/{self.model}",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=2000,
        )
        text = response.choices[0].message.content or "{}"
        # Parse JSON
        import re
        match = re.search(r'\{.*\}', text, re.DOTALL)
        if match:
            return json.loads(match.group())
        return {}
